/*
Select Q
*/

SELECT * FROM EMP,DEPT;
SELECT ENAME,HIREDATE FROM EMP;
SELECT ENAME,HIREDATE,DEPTNO FROM EMP WHERE JOB='CLERK';
SELECT ENAME,SAL FROM EMP WHERE SAL>2000;
SELECT ENAME FROM EMP WHERE ENAME LIKE '%a%';
SELECT ENAME FROM EMP WHERE LENGTH(ENAME)=5;
SELECT ENAME,HIREDATE FROM EMP WHERE HIREDATE LIKE '__-___-81' OR HIREDATE LIKE '__-___-82';
SELECT ENAME AS NAME,HIREDATE "START DATE" FROM EMP;
SELECT ENAME,HIREDATE FROM EMP ORDER BY HIREDATE;
SELECT ENAME,SAL FROM EMP ORDER BY SAL DESC;
SELECT ENAME||' OF DEPT '||DEPTNO||' EARNED '||COMM AS TITLE FROM EMP;
SELECT DISTINCT DEPTNO FROM EMP WHERE JOB='CLERK';