/*Single Row Q.txt
*/
SELECT LOWER(ENAME),SAL FROM EMP;
UPDATE EMP SET ENAME=LOWER(ENAME);
SELECT * FROM EMP WHERE LENGTH(ENAME)=5;
SELECT SUBSTR('hello',2,4) AS ANS FROM DUAL;
SELECT SUBSTR('hello welcome',-5,4) FROM DUAL;