/*
SUB QUERIES WITH SELECT.txt
*/

SELECT ENAME,JOB FROM EMP WHERE JOB=(SELECT JOB FROM EMP WHERE ENAME='jones');
SELECT E.ENAME,D.DNAME FROM EMP E INNER JOIN DEPT D ON E.DEPTNO=D.DEPTNO WHERE D.LOC=(SELECT LOC FROM DEPT WHERE DEPTNO=(SELECT DEPTNO FROM EMP WHERE ENAME='jones'));
SELECT ENAME FROM EMP WHERE SAL=(SELECT MIN(SAL) FROM EMP);
SELECT ENAME FROM EMP WHERE SAL!=(SELECT MIN(SAL) FROM EMP);	
SELECT * FROM EMP WHERE JOB IN (SELECT JOB FROM EMP WHERE DEPTNO=(SELECT DEPTNO FROM DEPT WHERE DNAME='SALES'));
SELECT ENAME FROM EMP WHERE DEPTNO IN (SELECT E.DEPTNO FROM EMP E INNER JOIN DEPT D ON D.DEPTNO=E.DEPTNO WHERE E.JOB='ANALYST');
/*
ALTERNATE FOR 6TH 
 SELECT ENAME FROM EMP WHERE DEPTNO IN (SELECT DEPTNO FROM EMP WHERE JOB='ANALYST');
 */
(SELECT ENAME,JOB,SAL AS CUR_SAL,SAL*1.07 AS RAISE FROM EMP WHERE JOB!='CLERK') UNION (SELECT ENAME,JOB,SAL AS CUR_SAL,SAL*1.1 AS RAISE FROM EMP WHERE JOB='CLERK');
SELECT ENAME,SAL,NVL(COMM,0) FROM EMP;
SELECT ENAME,(SAL+NVL(COMM,0)) AS EARNED FROM EMP;