/*
Group Functions Q
*/

SELECT MAX(SAL),MIN(SAL),AVG(SAL),MAX(COMM),MIN(COMM),AVG(COMM) FROM EMP;
SELECT DEPTNO,SUM(SAL) AS TOT_SAL ,SUM(COMM) AS TOT_COMM FROM EMP GROUP BY DEPTNO;
SELECT DEPTNO,SUM(SAL) AS TOT_SAL ,SUM(COMM) AS TOT_COMM FROM EMP WHERE COMM>0 GROUP BY DEPTNO;
SELECT DEPTNO,COUNT(*) AS NUM FROM EMP WHERE JOB='CLERK' GROUP BY DEPTNO;
SELECT DEPTNO,SUM(SAL) AS TOT_SAL FROM EMP GROUP BY DEPTNO HAVING COUNT(*)>3;
SELECT E.EMPNO,COUNT(*) FROM  EMP E INNER JOIN EMP D ON E.EMPNO=D.MGR GROUP BY E.EMPNO;
/*
ALTERNATE FOR 6TH
 select mgr,count(*) from emp where mgr is not null group by mgr;
*/
