/*
LIKE IS 
*/
SELECT * FROM EMP WHERE ENAME LIKE 's%';
SELECT * FROM EMP WHERE ENAME NOT LIKE '%s%';
SELECT * FROM EMP WHERE ENAME LIKE '_a%';
SELECT * FROM EMP WHERE HIREDATE LIKE '__-JAN-__';
SELECT * FROM EMP WHERE HIREDATE LIKE '__-___-81';
SELECT * FROM EMP WHERE HIREDATE LIKE '0_-___-__';
SELECT * FROM EMP WHERE SAL>999;
/*
ALTERNATIVE :-
USE SUBSTRING FUNCTION
SELECT * FROM EMP WHERE SAL LIKE '____';
*/
SELECT * FROM EMP WHERE COMM IS NULL;
SELECT * FROM EMP WHERE COMM IS NOT NULL;